# explore_node:
#   ros__parameters:
#     robot_base_frame: base_link
#     costmap_topic: /global_costmap/costmap
#     costmap_updates_topic: /global_costmap/costmap_updates
#     visualize: true
#     # 前沿更新频率（默认0.15，有点慢）
#     planner_frequency: 0.3
    
#     # x秒内没有靠近某个frontier，就认为该前沿不可达
#     progress_timeout: 45.0
    
#     # 距离越近的前沿得分越高（吸引力，默认3）
#     potential_scale: 3.0
    
#     # 朝向优化（默认0）
#     orientation_scale: 0.0
    
#     # 前沿包含的未知栅格越多 → 得分更高（收益，默认1）
#     gain_scale: 1.0
#     transform_tolerance: 0.3
    
#     # 一个frontier的最小面积（平方米）
#     min_frontier_size: 0.05

explore_node:
  ros__parameters:
    robot_base_frame: base_link
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: /global_costmap/costmap_updates
    visualize: true

    # 探索决策频率：慢一点，别在狭窄空间疯狂重选
    planner_frequency: 0.3

    # 给“绕路 / 退出狭窄空间”更多时间
    progress_timeout: 30.0

    # 降低“离我近就一定好”的吸引力
    potential_scale: 2.0

    # 不用朝向（保持 0）
    orientation_scale: 0.0

    # 降低“狭窄空间里小碎 frontier”的收益权重
    gain_scale: 1.0

    transform_tolerance: 0.3

    # 强力抑制“1~2 格宽的小 frontier”
    min_frontier_size: 0.1

