# 配置禁止通行区域（长方形）
bboxes:
  - frame: map
    # 四角坐标（必须按顺时针或逆时针顺序排列，形成闭合多边形）
    # 示例：矩形区域从 x=-2.0 到 x=1.0, y=-5.0 到 y=5.0
    corners:
      - [-2.0, -5.0]  # 左下角
      - [1.0, -5.0]   # 右下角
      - [1.0, 5.0]    # 右上角
      - [-2.0, 5.0]   # 左上角
  # - frame: map
  #   corners:
  #     - [-0.5, 1.0]
  #     - [-1.0, 1.0]
  #     - [-1.0, 2.0]
  #     - [-0.5, 2.0]
  # - frame: map
  #   corners:
  #     - [-1.5, -2.0]
  #     - [-1.0, -2.0]
  #     - [-1.0, -1.0]
  #     - [-1.5, -1.0]
  # - frame: map
  #   corners:
  #     - [1.5, 2.0]
  #     - [2.5, 2.0]
  #     - [2.5, 3.0]
  #     - [1.5, 3.0]



# grid parameters
resolution: 0.05 # 请和nav2的分辨率保持一致
topic: /keepout_filter_mask
publish_rate: 1.0
target_frame: map
# maximum allowed cells in generated grid (safety)
max_cells: 400000
